### ISSUE TITLE
Echo the GITHUB_TOKEN instead of cf_export to not output token

### ISSUE THREAD

**Issue by nesl247** [kostis-codefresh/github-pr-comment-step#2]
`cf_export`, for whatever wisdom of whoever designed this at CF, automatically outputs the value. This is insecure as it outputs the GitHub token. Instead, use the `echo` method to append to the `env_vars_to_export` file, or whatever the exact name is.

**Comment by kostis-codefresh** [comment]
Thanks for the feedback. I have updated the plugin and it shouldn't echo the value now.
